name: Dummy playgroumd
favicon: null
layout_spectrum: 0.8994280695915222
typography_spectrum: 0.030235129641368985
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffffe'
    - '#0c070d'
    - '#816e66'
    - '#c4c1ae'
    - '#9a2124'
  brandStrength: 0.3125
  lightness: 0.9764484679326415
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
